version: "3.7"

services:
  nat_router:
    image: alpine
    container_name: nat_router
    privileged: true # Grant full access to the container
    # Remember to set dns for packet fetching (google dns 8.8.8.8)
  command: >
      sh -c "
      echo 'nameserver 8.8.8.8' > /etc/resolv.conf &&
      apk add --no-cache iptables &&
      sysctl -w net.ipv4.ip_forward=1 &&
      iptables -t nat -A POSTROUTING -s 10.9.8.0/24 ! -o eth0 -j MASQUERADE &&
      iptables -A FORWARD -s 10.9.8.0/24 -j ACCEPT &&
      iptables -A FORWARD -d 10.9.8.0/24 -j ACCEPT &&
      sleep infinity
      "
  networks:
    ipvlan_base:
      ipv4_address: 10.9.8.254

networks:
  ipvlan_base:
    driver: ipvlan
    driver_opts:
      parent: eth0
      ipvlan_mode: l3
    ipam:
      config:
        - subnet: 10.9.8.0/24
