version: "3.7"

services:
  nat_router:
    build:
      context: .
      dockerfile: base.Dockerfile
    container_name: nat_router
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      ipvlan_base:
        ipv4_address: 10.9.8.254

networks:
  ipvlan_base:
    driver: ipvlan
    driver_opts:
      parent: eth0
      ipvlan_mode: l3
    ipam:
      config:
        - subnet: 10.9.8.0/24
        # gateway: 10.9.8.1
